import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document } from 'mongoose';

/**
 * Question Pattern Schema
 *
 * Stores core interview question patterns that rotate weekly.
 * Each pattern has multiple variations generated by AI.
 *
 * STRATEGY: 20 patterns × 4 weeks = 80 unique weeks before repetition
 */

@Schema({ timestamps: true })
export class QuestionPattern {
  @Prop({ required: true, enum: ['technical', 'behavioral', 'system_design'] })
  type: string;

  @Prop({ required: true })
  weekNumber: number; // 1-52 (week of year)

  @Prop({ required: true })
  patternName: string; // e.g., "Two Pointers", "Sliding Window", "Leadership"

  @Prop({ required: true })
  coreTemplate: string; // Base problem description

  @Prop({ type: [String], required: true })
  learningObjectives: string[]; // What user should learn

  @Prop({ type: [String], default: [] })
  relatedTags: string[]; // e.g., ['arrays', 'optimization']

  @Prop({ default: 0 })
  timesUsed: number; // Track popularity

  @Prop({ type: Date })
  lastUsedAt: Date;
}

export type QuestionPatternDocument = QuestionPattern & Document;
export const QuestionPatternSchema = SchemaFactory.createForClass(QuestionPattern);

// Indexes for efficient queries
QuestionPatternSchema.index({ type: 1, weekNumber: 1 });
QuestionPatternSchema.index({ patternName: 1 });
