import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export type NotificationLogDocument = NotificationLog & Document;

/**
 * Notification trigger types - reasons why a notification was sent
 */
export enum NotificationTrigger {
  /** User has a paused interview session > 24 hours */
  INCOMPLETE_INTERVIEW = 'incomplete_interview',
  /** User hasn't been active for 3+ days */
  LONG_ABSENCE = 'long_absence',
  /** User's last 3 interview scores are declining */
  SCORE_DECLINE = 'score_decline',
  /** User achieved a new personal best or streak */
  ACHIEVEMENT = 'achievement',
  /** Weekly progress summary (sent every Monday) */
  WEEKLY_PROGRESS = 'weekly_progress',
  /** First interview completed - congrats message */
  FIRST_INTERVIEW = 'first_interview',
  /** Trial ending soon reminder */
  TRIAL_ENDING = 'trial_ending',
  /** Onboarding survey for new users (3-4h after registration) */
  ONBOARDING_SURVEY = 'onboarding_survey',
  /** Profile incomplete - ask for position after 4h if still default */
  PROFILE_INCOMPLETE = 'profile_incomplete',
  /** Active job-seeker inactive for 24h - motivational nudge */
  JOBSEEKER_INACTIVE = 'jobseeker_inactive',
}

/**
 * Delivery status of the notification
 */
export enum NotificationDeliveryStatus {
  /** Successfully sent to user */
  SENT = 'sent',
  /** Failed to send (network error, etc.) */
  FAILED = 'failed',
  /** User has blocked the bot */
  BLOCKED = 'blocked',
  /** User account is deactivated */
  DEACTIVATED = 'deactivated',
}

@Schema({ timestamps: true, collection: 'notification_logs' })
export class NotificationLog {
  /** Reference to the user who received this notification */
  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  userId: Types.ObjectId;

  /** Telegram ID for quick lookup (denormalized for performance) */
  @Prop({ required: true, index: true })
  telegramId: number;

  /** What triggered this notification */
  @Prop({ type: String, enum: Object.values(NotificationTrigger), required: true })
  trigger: NotificationTrigger;

  /** The actual message content sent to user */
  @Prop({ required: true })
  content: string;

  /** When the notification was sent */
  @Prop({ required: true, index: true })
  sentAt: Date;

  /** 24-hour response window end time */
  @Prop({ required: true })
  responseWindowEndsAt: Date;

  /** Delivery status */
  @Prop({
    type: String,
    enum: Object.values(NotificationDeliveryStatus),
    default: NotificationDeliveryStatus.SENT,
  })
  deliveryStatus: NotificationDeliveryStatus;

  /** Error message if delivery failed */
  @Prop()
  deliveryError?: string;

  /** Whether user responded within the 24h window */
  @Prop({ default: false })
  responseReceived: boolean;

  /** When user responded (if they did) */
  @Prop()
  responseReceivedAt?: Date;

  /**
   * Whether this log has been processed by the scheduler (either responded or expired)
   * This prevents re-processing expired notifications multiple times
   */
  @Prop({ default: false, index: true })
  processed: boolean;

  /** Metadata for analytics and debugging */
  @Prop({
    type: Object,
    default: () => ({
      aiGenerated: false,
      consecutiveIgnoresAtSend: 0,
      language: 'uz',
    }),
  })
  metadata: {
    /** Was this message generated by AI? */
    aiGenerated?: boolean;
    /** AI model used (if any) */
    aiModel?: string;
    /** Tokens used for generation */
    tokensUsed?: number;
    /** User's consecutive ignore count at time of sending */
    consecutiveIgnoresAtSend?: number;
    /** Language the message was sent in */
    language?: string;
    /** Additional context (e.g., paused session ID, technology, etc.) */
    context?: Record<string, any>;
  };

  // Timestamps
  createdAt: Date;
  updatedAt: Date;
}

export const NotificationLogSchema = SchemaFactory.createForClass(NotificationLog);

// Indexes for efficient queries
// Find pending responses (sent but not responded within window)
NotificationLogSchema.index({ responseReceived: 1, responseWindowEndsAt: 1 });
// Find user's notification history
NotificationLogSchema.index({ userId: 1, sentAt: -1 });
// Analytics: Find by trigger type and date range
NotificationLogSchema.index({ trigger: 1, sentAt: -1 });
// Cleanup old logs
NotificationLogSchema.index({ createdAt: 1 }, { expireAfterSeconds: 90 * 24 * 60 * 60 }); // 90 days TTL
